# -------------------------------------------------------------------------------------------------
# Default settings for airdrops
# -------------------------------------------------------------------------------------------------
Airdrop:
  Default_Auto_Destroy_Time: 5 minutes # You can use seconds, minutes, hours as a time suffix
  Default_Range: 2000
  Default_Random_Location: true
  Broadcast_Location_On_Call: true

  # -------------------------------------------------------------------------------------------------
  # Attempt number to find suitable location for spawning airdrop.
  # If not found it'll be notified and airdrop won't spawn until next time.
  #
  # * If you found a problem that airdrop won't auto spawn or cannot find suitable location very often
  # try to increase the number.
  # -------------------------------------------------------------------------------------------------
  Location_Search_Attempts: 10




# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
#
# * THE FIRST ALIAS IS THE MAIN LABEL, PLEASE DO NOT REMOVE IT. *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [airdropx, airdrop]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied 
# to your messages/ folder where you can edit it.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured. You can also use the LagCatcher class to invoke
# this feature. We log a console message if an operation takes over the time below (milliseconds). 
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about their features.
# The Debugger class utilizes this key and will only print messages for sections enabled below.
# -------------------------------------------------------------------------------------------------
Debug: []

# -------------------------------------------------------------------------------------------------
# The AirdropX prefix. Highly recommend to leave it empty for beautiful.
# -------------------------------------------------------------------------------------------------
Prefix: ""

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1